/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xuansu_opencv_JniJavaActivity */

#ifndef _Included_com_xuansu_opencv_JniJavaActivity
#define _Included_com_xuansu_opencv_JniJavaActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xuansu_opencv_JniJavaActivity
 * Method:    getEdge
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_xuansu_opencv_JniJavaActivity_getEdge
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_xuansu_opencv_JniJavaActivity
 * Method:    grayProc
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_xuansu_opencv_JniJavaActivity_grayProc
        (JNIEnv *, jobject, jintArray, jint, jint);
#ifdef __cplusplus
}
#endif
#endif
